apiVersion: v2
name: maintenance
description: Quickly set up an elegant and user-friendly maintenance page for your services.
type: application
version: 0.1.6
appVersion: "1.20.0"
kubeVersion: ">=1.19.0-0"