name: make
on:
  release:
    types: [ published ]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  call-helm-chart-release:
    uses: ./.github/workflows/helm-chart-release.yml
    with:
      oci_repo: ghcr.io/qcdis
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}
